### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by moritzschindelmann** [javalite/simple-example#7]
After successfully following along the instructions of your ReadMe, the command line returns:
"Could not find or load main class"
when trying to execute:
java -classpath target/dependency:target/classes activejdbc.examples.simple.Main

Maven: 3.6.0
Java: jre1.8.0_191, jdk1.8.0_201

Best regards.

**Comment by ipolevoy** [comment]
I cannot reproduce your problem.  Make sure you followed all steps, including: `mvn dependency:unpack-dependencies`. 
If you still have a  problem, please post all steps and output here .

**Comment by moritzschindelmann** [comment]
Operating System: Windows 10 (64-bit).
All commands were executed in folder simple-example-master.

In fresh folder:
**mvn db-migrator:create** -> BUILD SUCCESS
**mvn db-migrator:migrate** -> BULD SUCCESS
**mvn clean install**: 
  Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.803 sec - in 
  activejdbc.examples.simple.MovieSpec
  ->BUILD SUCCESS
**mvn dependency:unpack-dependencies** -> BUILD SUCCESS
**java -cp target/dependency:target/classes -Dactivejdbc.log activejdbc.examples.simple.Main**
  Error: Could not find or load main class activejdbc.examples.simple.Main
**mvn process-classes** -> BUILD SUCCESS
**java -classpath target/dependency:target/classes -Dactivejdbc.log activejdbc.examples.simple.Main**
  Error: Could not find or load main class activejdbc.examples.simple.Main
**java -cp target/simple-example-1.0-SNAPSHOT.jar activejdbc.examples.simple.Main**
  Error: A JNI error has occurred, please check your installation and try again             
Exception in thread "main" java.lang.NoClassDefFoundError: org/javalite/activejdbc/Model  
        at java.lang.Class.getDeclaredMethods0(Native Method)                             
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)                      
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)                      
        at java.lang.Class.getMethod0(Unknown Source)                                     
        at java.lang.Class.getMethod(Unknown Source)                                      
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)                  
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)                   
Caused by: java.lang.ClassNotFoundException: org.javalite.activejdbc.Model                
        at java.net.URLClassLoader.findClass(Unknown Source)                              
        at java.lang.ClassLoader.loadClass(Unknown Source)                                
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)                     
        at java.lang.ClassLoader.loadClass(Unknown Source)                                
        ... 7 more

**Comment by ipolevoy** [comment]
See: https://stackoverflow.com/questions/54923978/javalite-could-not-find-or-load-main-class/54951756#54951756
